services:
- type:web
  name: boutique-projet
  env: python
  buildCommand: pip install -r requirements.txt && python manage.oy collectstatic --no-input && python manage.py migrate
  startCommand: gunicorn boutique_projet.wsgi:application 