# Generated by Django 6.0.4 on 2026-05-16 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commande',
            old_name='cleint_email',
            new_name='client_email',
        ),
        migrations.RenameField(
            model_name='commande',
            old_name='status',
            new_name='statut',
        ),
    ]
