# Generated by Django 6.0.4 on 2026-05-19 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0002_rename_cleint_email_commande_client_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='produits/'),
        ),
    ]
