# Generated by Django 6.0.4 on 2026-05-19 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0003_commande_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='image',
        ),
        migrations.AddField(
            model_name='produit',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='produits/'),
        ),
    ]
